<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="18" failures="18" errors="0" time="1.006">
  <testsuite name="Raindrops" errors="0" failures="18" skipped="0" timestamp="2023-06-28T14:20:42" time="0.67" tests="18">
    <testcase classname="Raindrops the sound for 1 is 1" name="Raindrops the sound for 1 is 1" time="0.001">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:4:52)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 3 is Pling" name="Raindrops the sound for 3 is Pling" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:6:56)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 5 is Plang" name="Raindrops the sound for 5 is Plang" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:8:56)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 7 is Plong" name="Raindrops the sound for 7 is Plong" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:10:56)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 6 is Pling as it has a factor 3" name="Raindrops the sound for 6 is Pling as it has a factor 3" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:13:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base" name="Raindrops 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base" time="0.001">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:16:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 9 is Pling as it has a factor 3" name="Raindrops the sound for 9 is Pling as it has a factor 3" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:19:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 10 is Plang as it has a factor 5" name="Raindrops the sound for 10 is Plang as it has a factor 5" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:22:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 14 is Plong as it has a factor of 7" name="Raindrops the sound for 14 is Plong as it has a factor of 7" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:25:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 15 is PlingPlang as it has factors 3 and 5" name="Raindrops the sound for 15 is PlingPlang as it has factors 3 and 5" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:28:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 21 is PlingPlong as it has factors 3 and 7" name="Raindrops the sound for 21 is PlingPlong as it has factors 3 and 7" time="0.001">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:31:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 25 is Plang as it has a factor 5" name="Raindrops the sound for 25 is Plang as it has a factor 5" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:34:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 27 is Pling as it has a factor 3" name="Raindrops the sound for 27 is Pling as it has a factor 3" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:37:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 35 is PlangPlong as it has factors 5 and 7" name="Raindrops the sound for 35 is PlangPlong as it has factors 5 and 7" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:40:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 49 is Plong as it has a factor 7" name="Raindrops the sound for 49 is Plong as it has a factor 7" time="0.001">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:43:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 52 is 52" name="Raindrops the sound for 52 is 52" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:45:54)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7" name="Raindrops the sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:48:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="Raindrops the sound for 3125 is Plang as it has a factor 5" name="Raindrops the sound for 3125 is Plang as it has a factor 5" time="0">
      <failure>TypeError: (0 , _raindrops.convert) is not a function
    at Object.&lt;anonymous&gt; (/projects/challenge/raindrops.spec.js:51:19)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:293:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:226:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:297:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:233:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:135:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:130:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:68:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
  </testsuite>
</testsuites>